# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HD4FSMlYx1h_cWOxKte8NDDSb5Y-ccdQ
"""

import sys
if 'google.colab' in sys.modules:
  !pip install streamlit
import streamlit as st
import pandas as pd
import joblib
import numpy as np

# 1. Load the model and columns
model = joblib.load('finguard_model.joblib')
model_columns = joblib.load('model_columns.joblib')

st.set_page_config(page_title="FinGuard Risk AI", page_icon="🛡️")
st.title("🛡️ FinGuard: Loan Risk Predictor")
st.markdown("### Optimized for High-Recall Default Detection")

# 2. Sidebar for User Inputs
st.sidebar.header("Applicant Information")
income = st.sidebar.number_input("Annual Income ($)", min_value=10000, max_value=250000, value=60000)
credit_score = st.sidebar.slider("Credit Score", 300, 850, 650)
loan_amount = st.sidebar.number_input("Loan Amount ($)", min_value=1000, max_value=50000, value=15000)
years_emp = st.sidebar.slider("Years of Employment", 0, 40, 5)
emp_type = st.sidebar.selectbox("Employment Type", ["Full-Time", "Part-Time", "Contract", "Self-Emp"])

if st.button("Analyze Risk"):
    # 3. Prepare the Input Data
    # Create a base dataframe with numerical inputs
    data = {
        'income': [income],
        'credit_score': [credit_score],
        'loan_amount': [loan_amount],
        'years_employment': [years_emp]
    }
    input_df = pd.DataFrame(data)

    # 4. Feature Engineering: Create DTI Ratio
    input_df['dti_ratio'] = input_df['loan_amount'] / input_df['income']

    # 5. One-Hot Encoding (Manual to match Training)
    # We must create columns for Full-Time, Part-Time, etc.
    for col in model_columns:
        if "employment_type_" in col:
            input_df[col] = 1 if f"employment_type_{emp_type}" == col else 0

    # Ensure column order matches training exactly
    input_df = input_df[model_columns]

    # 6. Apply Optimized Threshold (30%)
    prob_default = model.predict_proba(input_df)[:, 1][0]

    st.subheader("Results")
    if prob_default >= 0.30:
        st.error(f"⚠️ **HIGH RISK:** Likely to Default (Probability: {prob_default:.2%})")
        st.write("Reasoning: Low threshold (30%) triggered due to potential leverage or score anomalies.")
    else:
        st.success(f"✅ **LOW RISK:** Safe to Approve (Probability: {prob_default:.2%})")

    st.write("---")
    st.write("**Model Parameters:** Random Forest Classifier | Threshold: 0.30 | Class Weight: 2:1")