# -*- coding: utf-8 -*-
"""Capstone_Sneha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g1A4Jn--sVotH_lZFpcyplj2A_0uWkFl

Genereting a Synthetic Dataset of 1000 loan applicants
"""

import pandas as pd
import numpy as np

# Reproducibility
np.random.seed(42)

def generate_messy_loan_data(n=1000):
    # 1. Base Data Generation (Same logic as before)
    income = np.random.lognormal(mean=11, sigma=0.5, size=n)
    credit_score = np.random.randint(300, 850, size=n)
    loan_amount = np.random.uniform(5000, 45000, size=n)
    years_employment = np.random.randint(0, 40, size=n)

    # Target Logic
    risk_score = (850 - credit_score) * 0.5 + ((loan_amount / income) * 100)
    prob_default = 1 / (1 + np.exp(-(risk_score - 250) / 50))
    default = np.random.binomial(1, prob_default)

    df = pd.DataFrame({
        'income': income.round(2),
        'credit_score': credit_score,
        'loan_amount': loan_amount.round(2),
        'years_employment': years_employment,
        'default': default
    })

    # --- INJECTING THE MESSINESS ---

    # A. Missing Values (NaNs)
    # Simulate users skipping the 'income' or 'years_employment' field
    df.loc[df.sample(frac=0.05).index, 'income'] = np.nan
    df.loc[df.sample(frac=0.08).index, 'years_employment'] = np.nan

    # B. Impossible Outliers
    # Someone accidentally typed an extra zero or a negative number
    df.loc[0, 'income'] = 25000000  # A 25-million dollar income (Outlier)
    df.loc[5, 'credit_score'] = 9999 # Impossible credit score
    df.loc[10, 'years_employment'] = -5 # Negative employment years

    # C. Formatting Issues
    # Add a categorical column with inconsistent naming
    employment_types = ['Full-Time', 'Part-time', 'fulltime', 'Contract', 'self-emp']
    df['employment_type'] = np.random.choice(employment_types, size=n)

    return df

# Initialize the messy dataset
messy_loan_df = generate_messy_loan_data(1000)

print("--- Messy Data Preview ---")
print(messy_loan_df.head(10))

#Understaing the data, column types and null values
messy_loan_df.info()

#Gives you a quick statistical summary (mean, max, min) of your newly collected dataset.
messy_loan_df.describe()

#Let's deal with the null values
messy_loan_df.isnull().sum() #Count of null values each column

#Let's fill the missing nulls with mode
messy_loan_df['income'] = messy_loan_df['income'].fillna(messy_loan_df['income'].median())
messy_loan_df['years_employment'] = messy_loan_df['years_employment'].fillna(messy_loan_df['years_employment'].median())
messy_loan_df.info()

"""Data Cleaning\
Let's find if there is any duplicated or not, if there then remove duplicates
"""

#Find duplicates
messy_loan_df.duplicated().sum()

#Remove duplicate
messy_loan_df.drop_duplicates(inplace=True)
messy_loan_df.duplicated().sum()

#Finding the distinct values of emplyoee_type
messy_loan_df['employment_type'].value_counts()

# Let's remove the invalid spaces and fix the wordings
messy_loan_df['employment_type'] = messy_loan_df['employment_type'].str.strip().str.title()
messy_loan_df['employment_type'].value_counts()

#Let's map the right words
mapping = {'Fulltime':'Full-Time'}
messy_loan_df['employment_type'] = messy_loan_df['employment_type'].replace(mapping)
messy_loan_df['employment_type'].value_counts()

assert messy_loan_df['years_employment'].min() <=0

"""Outlier Handling"""

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10, 4))
sns.boxplot(x=messy_loan_df['income'])
plt.title('Identifying Income Outliers')
plt.show()

#Using IQR methode to fix the income outlier
Q1 = messy_loan_df['income'].quantile(0.25)
Q3 = messy_loan_df['income'].quantile(0.75)

#IQR
IQR = Q3 -Q1

#Define the 'Fence'
lower_fence = Q1 - 1.5 * IQR
upper_fence = Q3 + 1.5 * IQR

#Capping the outlier to the upper bound so we don't loose the data
messy_loan_df['income'] = messy_loan_df['income'].clip(lower= lower_fence, upper = upper_fence)
messy_loan_df['income'].max()

#Logic to fix the negetive Employement
messy_loan_df['years_employment'] = messy_loan_df['years_employment'].clip(lower = 0)
messy_loan_df['years_employment'].min()

#Logic to clip outlier to Credit scrore
messy_loan_df.loc[messy_loan_df['credit_score'] > 850, 'credit_score'] = 850
messy_loan_df['credit_score'].max()

messy_loan_df.describe()

"""EDA"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x = 'employment_type',data = messy_loan_df)
plt.show()

sns.histplot(data = messy_loan_df['income'], kde=True)
plt.show()

plt.figure(figsize=(10, 6))
sns.barplot(data=messy_loan_df, x='employment_type', y='credit_score', estimator='mean', palette='viridis')
plt.title('Average Credit Score per Employment Category')
plt.ylabel('Mean Credit Score')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(data=messy_loan_df, x='default', y='income', palette='Set2')
plt.title('Income Distribution: Paid (0) vs. Default (1)')
plt.show()

_plt.figure(figsize=(10, 8))
correlation_matrix = messy_loan_df.corr(numeric_only=True)
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.show()

sns.pairplot(messy_loan_df, hue = 'credit_score')
plt.show()

"""To handle categorical data, I implemented One-Hot Encoding for the 'Employment Type' feature. This converted qualitative categories into binary indicators, allowing the Random Forest algorithm to interpret employment stability as a numerical weight without assuming an inherent ranking between categories"""

# 1. Perform One-Hot Encoding on the 'employment_type' column
# 'drop_first=True' is a best practice to avoid the "dummy variable trap" (multicollinearity).
final_df = pd.get_dummies(messy_loan_df, columns=['employment_type'], drop_first=True)

# 2. Convert Boolean (True/False) to Integers (1/0)
# Recent versions of Pandas return True/False for dummies; we need 1/0 for Scikit-Learn.
final_df = final_df.astype({col: 'int' for col in final_df.columns if 'employment_type' in col})

# 3. Final Verification of the Dataset
print("--- Final Encoded Features ---")
print(final_df.columns.tolist())

# 4. Define Features (X) and Target (y)
# X contains all our 'clues' (income, credit score, etc.).
# y contains the 'answer' we want to predict (default).
X = final_df.drop('default', axis=1)
y = final_df['default']

print(f"\nFeature Shape: {X.shape}") # Should be (1000, Number of Features)
print(f"Target Shape: {y.shape}")

final_df.head()

"""I selected a Random Forest Classifier due to its ability to handle non-linear relationships between financial features without requiring extensive feature scaling. The model achieved an accuracy of 79%, successfully identifying patterns between credit scores and loan-to-income ratios."""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# 1. Split the data into Training (80%) and Testing (20%) sets
# We use 'stratify=y' to ensure the percentage of defaults is the same in both sets.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

# 2. Initialize the Random Forest Classifier
# n_estimators=100 means we are using 100 individual decision trees to vote.
rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)

# 3. Train the model (The "Learning" phase)
rf_model.fit(X_train, y_train)

# 4. Make predictions on the Test Set
y_pred = rf_model.predict(X_test)

# 5. Output the performance metrics
print("--- Model Performance ---")
print(f"Overall Accuracy: {accuracy_score(y_test, y_pred):.2%}")

print("\n--- Detailed Classification Report ---")
# This shows Precision and Recall, which is vital for financial risk.
print(classification_report(y_test, y_pred))

# 1. Combine the test features with the actual and predicted results
results_df = X_test.copy()
results_df['Actual_Default'] = y_test
results_df['Predicted_Default'] = y_pred

# 2. Isolate 'False Negatives' (Model said "Paid", but they actually "Defaulted")
# These are the most critical failures for a loan risk model.
false_negatives = results_df[(results_df['Actual_Default'] == 1) & (results_df['Predicted_Default'] == 0)]

# 3. View the top 5 failures to analyze
print("--- Model Failure Examples (False Negatives) ---")
print(false_negatives.head(5))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap='Blues')
plt.title('FinGuard Model: Confusion Matrix')
plt.show()

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# --- 1. FEATURE ENGINEERING: Creating the DTI (Debt-to-Income) Ratio ---
# We help the model by explicitly calculating the 'leverage' variable.
final_df['dti_ratio'] = final_df['loan_amount'] / final_df['income']

# Update X and y with the new feature
X = final_df.drop('default', axis=1)
y = final_df['default']

# Split data (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# --- 2. HYPERPARAMETER TUNING: Class Weighting ---
# We tell the model that missing a Default (1) is twice as 'expensive' as
# missing a Paid loan (0) using 'class_weight'.
rf_optimized = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    class_weight={0: 1, 1: 2}, # Default (1) is weighted 2x
    random_state=42
)

rf_optimized.fit(X_train, y_train)

# --- 3. THRESHOLD ADJUSTMENT: Shifting from 50% to 30% ---
# Instead of using .predict(), we get the raw probabilities.
# Column 0 is prob(Paid), Column 1 is prob(Default).
y_probs = rf_optimized.predict_proba(X_test)[:, 1]

# If the probability of default is > 30%, we classify as Default (1).
custom_threshold = 0.3
y_pred_optimized = (y_probs >= custom_threshold).astype(int)

# --- 4. FINAL EVALUATION ---
print("--- Optimized Model Performance (30% Threshold) ---")
print(classification_report(y_test, y_pred_optimized))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred_optimized)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap='Blues')
plt.title('FinGuard Model: Confusion Matrix')
plt.show()

# 1. Combine the test features with the actual and predicted results
results_df = X_test.copy()
results_df['Actual_Default'] = y_test
results_df['Predicted_Default'] = y_pred_optimized

# 2. Isolate 'False Negatives' (Model said "Paid", but they actually "Defaulted")
# These are the most critical failures for a loan risk model.
false_negatives = results_df[(results_df['Actual_Default'] == 1) & (results_df['Predicted_Default'] == 0)]

# 3. View the top 5 failures to analyze
print("--- Model Failure Examples (False Negatives) ---")
print(false_negatives.head(5))